<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">changePoolSize</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXIgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCg0KdHJ5IHsN
CgkNCglTdHJpbmcgcG9vbCA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXIsICJwb29s
Iik7DQoJDQoJU3RyaW5nIHNQb29sU2l6ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVD
dXIsICJuZXdQb29sU2l6ZSIpOw0KCWludCBwb29sU2l6ZSA9IEludGVnZXIudmFsdWVPZihzUG9v
bFNpemUpOw0KCQ0KCWlmKHBvb2xTaXplIDw9IDApIHsNCgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNl
cHRpb24oIm1heFRocmVhZHMgdmFsdWUgbXVzdCBiZSBwb3NpdGl2ZSIpOw0KCX0gZWxzZSBpZihw
b29sU2l6ZSA+IE1BWF9USFJFQURTKSB7DQoJCXBvb2xTaXplID0gTUFYX1RIUkVBRFM7DQoJfQ0K
CQ0KCVJlYWN0aXZlV01GYWNhZGUuY2hhbmdlUG9vbFNpemUocG9vbCwgcG9vbFNpemUpOw0KCQ0K
fSBjYXRjaChFeGNlcHRpb24gZSkgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOw0K
fSBmaW5hbGx5IHsNCglpZihwaXBlbGluZUN1ciAhPSBudWxsKSB7DQoJCXBpcGVsaW5lQ3VyLmRl
c3Ryb3koKTsNCgl9DQp9</value>
</Values>
